// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cellula-homepage/LabReport.tsx": () => import("../components/mockups/cellula-homepage/LabReport.tsx"),
  "./components/mockups/cellula-homepage/QuietDark.tsx": () => import("../components/mockups/cellula-homepage/QuietDark.tsx"),
  "./components/mockups/cellula-homepage/SwissGrid.tsx": () => import("../components/mockups/cellula-homepage/SwissGrid.tsx")
};
